### ISSUE TITLE
Requirements: kubernetes support

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#105]
There are several ways we can support kubernetes, with different levels of VIC exploitation. The different approaches need to be characterized and assessed for viability given current and pending VIC capabilities.

Output:
- [ ] Design doc with details of possible approaches, pros & cons, and corresponding requirements on VIC
- [ ] Collection of more detailed customer requirements around k8s support to vet approaches
- [ ] Follow up issues for continuation

**Comment by urfuwo** [comment]
Hi all,
what happened to this feature? We are considering at SAP to start exploring vic, but this makes only sense if we have a process to use it in conjunction with kubernetes.
are you still planning on delivering support for kubernetes? any timeline ideas?
M.

**Comment by mdubya66** [comment]
@urfuwo sorry we missed your note on 30 Aug. We Do plan on delivering support for kubernetes. No timeline however. We will move this issue into our Backlog when we are able to take it on.

**Comment by hickeng** [comment]
## Moved from original description

After speaking to @imkin about it the kube-apiserver seems like the best current personality fit if we were to take the approach of supplying a kubernetes personality on a VCH.
How and where in the kubernetes stack integration with the port layer happens isn't at all clear at this point.

Proposal:

!! Discard concept of Node for now - most of the purposes of kubelet as a singleton per node are lost when running in the context of a VCH/vSphere cluster.
- On VCH appliance (if it needs vSphere access)
  - Controller Manager/scheduler
  - Kubelet - translates from Port Layer or Docker API to Kubelet API
- As containerVMs
  - API server
  - etcd (per ESX host)
  - kube proxy - could simply create nginx container, NSX integration longer term.

Kubelet talks to:
- Docker API for:
  - stats
  - resource consumption
  - running containers
