### ISSUE TITLE
Phone home integration

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#119]
Add basic phone home integration to the VCH, such that we get metrics:
- VCH successful initialization
- VCH initialization reason (deploy, update, upgrade)
- VCH failed initialization (failing stage)
- stats on images used from public repos
- stats on images used from private repos (coarse and anonymous)
- coarse metrics on container lifetimes (preferably correlated with base image in some manner)

This is split into distinct portions - split this out into discrete defects for visibility:
- [ ] common client code checked into pkg/vmware/ceip
- [ ] reporting via client for the instant data items, e.g. appliance initialization success/fail
- [ ] data collection and consolidation for batched reporting
- [ ] batched data reporting via client.

**Comment by mdubya66** [comment]
1.1 feature request.
From @karthik-narayan via email
Our tools needs to return a custom value - “Photon OS – VCH “ and “Photon OS – Pico”  or some such thing. 

Here is the data from phone home that I’d like to see per deployment: 
Number of ESX hosts in the cluster
Version number of ESX hosts 
Version number of VC hosts 
Presence of Harbor or Admiral with version number
Total number of VMs
Total number of VCHs
Total number of container VMs
Number of VCHs per host
Number of container VMs per VCH
Average lifetime of the Container VMS
Most common images deployed
Image source 
Most common list of docker commands used
Is port mapping used, if so how often
Except for 11,12,13 and 14, I believe that all other data can be auto generated / collected by VAC, if we are able to update our tools. 11,12,13 and 14 are nice to have for the Q1 release.
