### ISSUE TITLE
Image manifest JWS verification

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#1331]
**Story**
As a user I want to know that the image I pull has not been tampered with

**Details**
Implementation of the JWS signature validation on image manfiests should be performed in the `lib/imagec` code.
The digest for the image layers is already computed and verified by the portlayer.WriteImage call
  - [ ] verify that the layer digests are passed to this call

There should be no provision for accepting an image that fails signature validation if a signature is present.

**Acceptance**
- [ ] layer with checksum that does not match the layer digest - should be rejected
- [ ] image manifest that fails validation via JWS signature - should be rejected
- [ ] layers and images with correct digests should be accepted

bug1727662

**Comment by mdubya66** [comment]
@hickeng who should take this on? is it GA?

**Comment by mdubya66** [comment]
Moving to Icebox per 9/20 Triage. Needs release note.

**Comment by stuclem** [comment]
Already in the release notes, so removing the kind/note tag.

**Comment by mdubya66** [comment]
Low for 1.1 unless required by Harbor

**Comment by gigawhitlocks** [comment]
# Table of Contents

1.  [Layer signing in Docker image manifests for VIC](#org5161487)
    1.  [Issues](#orgdd89535)
        1.  [Image manifest JWS verification (epic)](#org9958d16)
        2.  [Validate JWS signatures of image manifests](#org997df4a)
        3.  [Create malformed image layer](#org85733c1)
        4.  [Create malformed image digest](#org651a9ff)
    2.  [Related resources](#org0e59177)
        1.  [Docker manifest signing definition](#orgfa80636)
        2.  [JWS definition](#org6584c12)
    3.  [Approach / Implementation](#orgc4255ab)
        1.  [Feature development will satisfy issue #4689](#org7a3db9a)
        2.  [Use Docker's libtrust for validating the signatures](#orgb287474)
        3.  [Call into JWS code from imagec](#org70925e8)
    4.  [Testing and Acceptance Plan](#org7982da9)
        1.  [Issues #4691 and 4690 will be satisfied via feature testing](#orgd2ebd45)
        2.  [Issue #4689 should provide unit tests](#org51ab756)


<a id="org5161487"></a>

# Layer signing in Docker image manifests for VIC


<a id="orgdd89535"></a>

## Issues


<a id="org9958d16"></a>

### [Image manifest JWS verification (epic)](https://github.com/vmware/vic/issues/1331)


<a id="org997df4a"></a>

### [Validate JWS signatures of image manifests](https://github.com/vmware/vic/issues/4689)


<a id="org85733c1"></a>

### [Create malformed image layer](https://github.com/vmware/vic/issues/4690)

1.  We might be able to reuse the one from [the tarball exploit's pull case](https://github.com/vmware/vic/pull/7408)


<a id="org651a9ff"></a>

### [Create malformed image digest](https://github.com/vmware/vic/issues/4691)

1.  Again, see the test from the [the tarball exploit's pull case](https://github.com/vmware/vic/pull/7408).


<a id="org0e59177"></a>

## Related resources


<a id="orgfa80636"></a>

### [Docker manifest signing definition](https://docs.docker.com/registry/spec/manifest-v2-1/#manifest-field-descriptions)

Example:

    "signatures": [
       {
          "header": {
             "jwk": {
                "crv": "P-256",
                "kid": "OD6I:6DRK:JXEJ:KBM4:255X:NSAA:MUSF:E4VM:ZI6W:CUN2:L4Z6:LSF4",
                "kty": "EC",
                "x": "3gAwX48IQ5oaYQAYSxor6rYYc_6yjuLCjtQ9LUakg4A",
                "y": "t72ge6kIA1XOjqjVoEOiPPAURltJFBMGDSQvEGVB010"
             },
             "alg": "ES256"
          },
          "signature": "XREm0L8WNn27Ga_iE_vRnTxVMhhYY0Zst_FfkKopg6gWSoTOZTuW4rK0fg_IqnKkEKlbD83tD46LKEGi5aIVFg",
          "protected": "eyJmb3JtYXRMZW5ndGgiOjY2MjgsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxNS0wNC0wOFQxODo1Mjo1OVoifQ"
       }
    ]


<a id="org6584c12"></a>

### [JWS definition](http://self-issued.info/docs/draft-ietf-jose-json-web-signature.html)


<a id="orgc4255ab"></a>

## Approach / Implementation


<a id="org7a3db9a"></a>

### Feature development will satisfy [issue #4689](https://github.com/vmware/vic/issues/4689)


<a id="orgb287474"></a>

### Use Docker's libtrust for validating the signatures

1.  [JWS verification in the Docker codebase](file:///home/ian/go/src/github.com/vmware/vic/vendor/github.com/docker/libtrust/jsonsign.go)

2.  [Verify()](file:///home/ian/go/src/github.com/vmware/vic/vendor/github.com/docker/libtrust/jsonsign.go) verifies the image based on its signature, afaict

    1.  This method returns a list of keys used to sign.
    
    2.  TODO Presumably these must be checked against the registry's cert?


<a id="org70925e8"></a>

### Call into JWS code from imagec

1.  Verify each layer based on its signature [In PullImage](file:///home/ian/go/src/github.com/vmware/vic/lib/imagec/imagec.go)

    Definitely after this codeblock
    
        // Pull the image manifest
        if err := ic.pullManifest(ctx); err != nil {
          return err
        }
        log.Infof("Manifest for image = %#v", ic.ImageManifestSchema1)
    
    Possibly before this one (but we might need `layers` below)
    
        // Get layers to download from manifest
        layers, err := ic.LayersToDownload()
        if err != nil {
          return err
        }
        ic.ImageLayers = layers
    
    but <span class="underline">definitely</span> before this gets called (immediately after the above)
    
        // Download all the layers
        if err := ldm.DownloadLayers(ctx, ic); err != nil {
          return err
    
    we need to define a function called something like `VerifyManifestSignature` which will return `err != nil` (or `false`) if the manifest appears to be tampered with, judging by a signature failure.

2.  Fail before downloading the layers if possible

    -   This should be possible because the signature is computed using the blobSums and the layers have to match their sums
    -   If the signature is bad, we can bail before downloading images
    -   If the signature is correct but then we receive data that does not match the provided blobSum in the manifest, we *should already fail* in this case, but we should take the opportunity to:
        -   Verify this behavior occurs and add it if it does not
        -   Verify that images that do not complete a `pull` do not leave around old layers
        -   Verify that this behavior is well-tested to prevent regressions

3.  VerifyManifestSignature

    VerifyManifestSignature will look roughly like this.
    
        func (ic *ImageCache) VerifyManifestSignature(manifest string) bool {
        /*  Read in the manifest from memory (ic.ImageManifestSchema1)
            Pass it to the Docker code, and look at the results to determine whether the signature is valid or not
            Return false if invalid, true if it is
        */
        }


<a id="org7982da9"></a>

## Testing and Acceptance Plan


<a id="orgd2ebd45"></a>

### Issues #[4691](https://github.com/vmware/vic/issues/4691) and [4690](https://github.com/vmware/vic/issues/4690) will be satisfied via feature testing

1.  A layer is an uncompresed tar

2.  A blobSum is a sha256 sum

3.  Given the above:

    1.  The test should be provided with a tarball of some files with its sha256 sum
    2.  The test should verify that incorrect blobSum *or* file results in a pull failure
    3.  The test should verify that it is not possible to inject the tarball into a `pull` operation even if the blobSum matches the injected data.
    4.  [The MITM test in the Docker Pull suite](file:///home/ian/go/src/github.com/vmware/vic/tests/test-cases/Group1-Docker-Commands/1-02-Docker-Pull.robot) will fail once this change is properly implemented, because that test exploits the fact that #3 is currently not met. The test injects a layer w/ a correct blobSum. This should not be possible. That test will have to be redesigned.


<a id="org51ab756"></a>

### Issue #4689 should provide unit tests

1.  `VerifyManifestSignature` should be well defined:

    -   Input should be a manifest
    -   Output should be either a bool (true or false representing validly or invalidly signed manifest) or an err (`nil` to represent success, some `err` to report a failed verification)

2.  Unit tests should be able to provide pre-created manifests and see if they validate
