### ISSUE TITLE
Appliance internal name resolution

### ISSUE THREAD

**Issue by emlin** [vmware/vic#338]
We need function to support conversion from user friendly name to ID used in our system. For example, user will call our CLI to create container with image name busybox:latest, so we need to translate the image name and tag to one internal ID, so that the correct image file is pulled out from internal image cache.
Another example is for command "docker start boring_einstein" or > "docker start 123ef876be", the name should be converted to the ID persisted in our system.
This function will span API server and image port layer, but I didn't try to separate the issues to different module, cause we'll need a consistent solution for all modules. But we don't have to have one single service only.
This issue is not for short term solution to meet OSS deadline.

Requirement:
- [ ] Translate image name with tag to image ID and vise versa
- [x] Translate image name without tag to image ID
- [x] Complete image ID from a short name if there is no duplicate
- [ ] Query back if image exists or not with both ID or name (the cache information should be consistent with real image status, to avoid translate non-exist image name:tag to one ID)
- [x] Translate container name to container ID and vise versa
- [x] Generate random name for container
- [ ] Query back if container exists or not. (Same to image query)

Investigation:
- [ ] How docker is doing this
- [ ] If docker code is standalone enough to be reused.

Design Consideration (issues need more discussion):
- [ ] Where to put this module. It should serve API server and port layer server
- [ ] To make the information available after service reboot, we'll need persistence mechanism. The possible solution is to write into ESXi, or with our own, e.g. etcd.
- [ ] As it's actually for container and image meta data persistent and query, besides of name and ID, we need to think about other attributes at the same time.

**Comment by hickeng** [comment]
This closely relates to the docker personalities in memory data structures that support name mapping, filters such as 'after' and anything depending on relationships between layers and/or containers.

**Comment by hickeng** [comment]
@corrieb Assigning this to you - we should have a chat about how to accomplish this cleanly, where we can share with DNS, etc.

**Comment by corrieb** [comment]
I can't size this until I'm clear on what work is involved. Will try to make time with George today.

**Comment by hickeng** [comment]
Closing this - it may come up again when we're talking about direct usage of the port layer.
For now the problem is addressed and the name <-> ID mapping is managed in the personality.
