### ISSUE TITLE
Investigate a potential role of containerd in VIC Engine

### ISSUE THREAD

**Issue by vburenin** [vmware/vic#3629]
As a developer, I need to understand a role of containerd in VIC engine life in order to figure out what our next steps should be.

## Work items
- [ ] Investigate containerd and make it working locally if it is possible.
- [ ] Figure out how docker is using containerd, where it sits and how calls are made.
- [ ] Start contributing into containerd project as simple bug fixes if possible.
- [ ] Get in touch and meet with containerd dev team if possible.
- [ ] Document findings about containerd.
