### ISSUE TITLE
Docker API: Container Operations (Parent Issue)

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#371]
Implement all the container operations that VIC support in the engine-api server.  Here are the list of container operations and any issue number for them.

- [ ] #369 List
- [x] #141 Create (initial implementation done PR #347)
- [ ] #370 Inspect
- [ ] List processes in container
- [ ] #366 Logs
- [ ] Inspect changes to container file system
- [ ] #376 Export container
- [ ] #386 Container resource usage
- [ ] #680 Resize container TTY
- [x] #301 Start container
- [ ] #363 Stop container
- [ ] #377 Restart container
- [ ] #378 Kill a container
- [ ] #379 Update a container
- [ ] #380 Rename a container
- [ ] #381 Pause a container
- [ ] #382 Unpause a container
- [ ] #362 Attach to a container
- [ ] Attach to a container (websocket)
- [ ] #384 Wait a container
- [ ] #364 Remove a container
- [ ] #385 Copy files or folders from a container
- [ ] Retrieving information about files and folders in a container
- [ ] Get an archive of a filesystem resource in a container
- [ ] Extract an archive of files or folders to a directory in a container

**Comment by mdubya66** [comment]
@hickeng please review.

**Comment by mdubya66** [comment]
Closing. Tracked in other ways
