### ISSUE TITLE
Docker API: Image Operations (Parent Issue)

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#372]
Implement all the image operations that VIC support in the engine-api server. Here are the list of image operations and any issue number for them.
- [ ] #387 List Images
- [ ] Build image from a Dockerfile
- [x] #135 Create an image (pull)
- [ ] #388 Inspect an image
- [ ] Get the history of an image
- [ ] Push an image on the registry
- [ ] #1120 Tag an image into a repository
- [ ] #365 Remove an image
- [ ] Search images

**Comment by mdubya66** [comment]
Image tag is requested for 1.1. Marking as medium for this purpose.
