### ISSUE TITLE
Docker API: Docker Misc Operations (Parent Issue)

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#373]
Implement all the misc operations that VIC support in the engine-api server. Here are the list of misc operations and any issue number for them.

- [ ] Check auth configuration
- [ ] Display system-wide information
- [ ] Show the docker version information
- [ ] Ping the docker server
- [ ] Create a new image from a container’s changes
- [ ] Monitor Docker’s events
- [ ] #501 Get a tarball containing all images in a repository
- [ ] Get a tarball containing all images.
- [ ] Load a tarball with a set of images and tags into docker
- [ ] Image tarball format
- [ ] Exec Create
- [ ] Exec Start
- [ ] Exec Resize
- [ ] Exec Inspect

**Comment by hickeng** [comment]
This is in backlog until all of the child operations have corresponding issues associated with them and those are correctly placed for inclusion in GA.

**Comment by mdubya66** [comment]
@hickeng what to do with this one

**Comment by mdubya66** [comment]
Closing, tracked in other ways
