### ISSUE TITLE
Milestone: engine notary support

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#4450]
**Story**
As a user I want to have confidence that the bytes I am using are the bytes I think I'm using, and that the author is known.
As a user I want to have confidence that the bytes I am using are the bytes I should be using given the application I'm running
As an admin I want to know that bytes used by users are from trusted sources and are use in an appropriate manner

**Details**
All trust is associated with tags - in a VCH, the portlayer is unaware of tags (these are a personality facet) - the implication is that the verification must be done in the personality side.

Trust level that can be applied to entities:
- blind (trust anything, don't vet signature)
- insecure (trust anything, confirm signature)
- TOFU (trust anything, confirm stable)
- secure (require verification via prior knowledge - ie. known CA)

Remote entities involved in image publishing/acquisition:
- notary
- registry
- repository
- tag

Registry is a hierarchy of:
- server
  - repository
    - tag

Each element in the registry should have:
- trust setting
- inheritable trust setting
  - specific trust setting overrides inherited?

Knowledge needed by a VCH:
- default registry
- notary configs
  - trust level
  - CA
- registry configs
  - trust level
  - CA
- repository configs
  - trust level
  - CA if secure & not TOFU
- tag configs
  - trust level
  - CA if secure & not TOFU

Tasks - basic support for notary:
- [ ] image signature validation (#1331)

Tasks - VCH support for notary:
- [ ] provide basic notary configuration to VCH (just a server?)
- [ ] default registry configuration
- [ ] add notary client support to the personality
- [ ] provide rich trust-level configuration

**Questions**
- How are repository keys stored, and how are they associated with repositories? Push example of `otherimage:latest` [here](https://docs.docker.com/engine/security/trust/content_trust/#push-trusted-content) shows that docker has detected that a new repository key is required.
- Does the docker server get involved in this, or is it purely client side?
  - as best I can tell the only server side requirement with the docker model is image signing.
- Do we want to whitelist entire registries (e.g. internal product registry) or just fully qualified repositories (registry/repository)
- What is the relationship arity between registry and notary - looks like it might be: notary server holds registry list, notary client gets registry list from server, notary client does something with that information

**Comment by mdubya66** [comment]
@karthik-narayan can you validate this against what is expected?
