### ISSUE TITLE
Portlayer: offline copy via disk attach

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5295]
**Story**
As a VIC developer I want a copy API implementation for when the target container is powered *off*
As a Port Layer caller I want a copy API that doesn't require knowledge of target state

**Detail**
Copying files to/from a container disk while the container is off requires attaching the VMDK to the endpoint VM, mounting it, then extracting or injecting the files.
Container disk should be detached on both success and error paths.
Parallel copying of files from multiple docker clients should be blocked, otherwise we cannot ensure consistency.
Attempts to power on container while disk is attached to endpoint should be blocked or rejected.

**Questions**
- [X] what is the expected behaviour when it comes to volumes and files on volumes - are copyFrom/copyTo symmetric in their behaviour with respect to volumes?
  - recursion into volumes is the responsibility of the caller to the Import/Export endpoints defined in #5321  and behaviour should be symmetrical. For a full implementation the caller should ensure that recursion into volumes occurs.

**Acceptance**
- [x] file copy into container - subsequent start of container shows file structure in container
- [x] file copy out of container - file structure present on client system
- [ ] container disks are not attached to endpoint irrespective of success or error paths
- [x] parallel copy requests do not collide
- [x] container start should not attempt to power on the container while copy is in progress - fails with X in use.
- [ ] container should start successfully even if endpointVM goes down in the middle of copying - does fsck and journal replay get performed correctly?

**Comment by matthewavery** [comment]
We must know in the portlayer whether the directory override flag is set or not. Since we are mounting the disk directly to the VCH.

**Comment by hickeng** [comment]
Added the dependency with ReadImage - this isn't a new dependency but simply captures the fact that the backend portion of diff has to do essentially the same work in the copyFrom case.

For the copyTo scenario we have two options:
1. add a new portlayer endpoint specifically for copying files into a container
2. update WriteImage to be able to write directly to an existing image if it has no children.

My preference is (2) from a gut feel - I'd prefer to have time to think through the implications but doubt that'll be available. Primary concerns for (2):
* increased conceptual complexity for the call as it's no longer write-once then immutable.
* changing one of our core paths could introduce/expose bugs (while we shouldn't be making decisions based on this issue, but it has to be mentioned given time considerations).
