### ISSUE TITLE
Portlayer: online copy via toolbox

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#5296]
**Story**
As a VIC developer I want a copy API implementation for when the target container is powered *on*
As a Port Layer caller I want a copy API that doesn't require knowledge of target state

**Detail**
Copying files to/from a container disk while the container is *on* requires using the DnD (drag and drop) mechanisms from toolbox guest operations.
Parallel copying of files should be viable, but for consistency with offline copy we should block this.
Attempts to power off container while copy is in progress should block until copy is complete, or until force is specified.

**Acceptance**
- [ ] file copy into container - container shows file structure in container
- [ ] file copy out of container - file structure present on client system
- [ ] parallel copy requests do not collide
- [ ] container stop should not attempt to power off the container while copy is in progress unless --force is specified
- [ ] copying file out of container should not block writing of that file in the container (e.g. copying a live log).

**Comment by matthewavery** [comment]
Tether will need the directory overwrite flag pushed to it in some way in order to identify how we want to do live file copies in the tether using the guest tools.
