### ISSUE TITLE
Continuous Integration v2

### ISSUE THREAD

**Issue by gigawhitlocks** [vmware/vic#6164]
Planning story for building out requirements for new or upgraded CI:

- [ ] Inventory available and currently used resources and available contributor skillsets
- [ ] Able to run tests against VC
- [ ] Mature CI software that doesn't make us hate ourselves
- [ ] Monitoring for CI infrastructure to prevent discovering resource limitations only when builds begin to fail
- [ ] Developer-friendly CI tools e.g. monitoring builds & recreating builds locally. Should be trivial to run tests on local compute (e.g. developer laptop) in a way that gives assurance that a test run in CI will pass (replicateable execution environment ideally with configuration-as-code)
- [ ] Dogfood.
- [ ] OVA build & testing
Will add to this as I continue to brainstorm. Please feel free to leave comments.

**Comment by sgairo** [comment]
@gigawhitlocks after you look into this more and feel comfortable with it, could you add your best estimate to the issue?

**Comment by hmahmood** [comment]
This should be broken up into issues and made an epic.

**Comment by chengwang86** [comment]
I think monitoring of CI test stats is also worth improving. @jakedsouza had a database and GUI to collect and display the ci test stats, e.g., which sub-test takes the longest time to run, which test suite fails most frequently. It definitely needs improvement. For example, we need documentation on how to query the database and generate stat graphs; we also need to be able to collect stats over a moving window instead of always starting from the first time we run the ci tests.

**Comment by gigawhitlocks** [comment]
This is now an epic and will be adding/sizing/prioritizing issues within it.

**Comment by gigawhitlocks** [comment]
I'm sure I'm missing some stuff we've already talked about, and some stuff we haven't thought of yet. Feel free to add issues to this epic.

**Comment by mdharamadas1** [comment]
@gigawhitlocks Here are my thoughts based on the discussions so far. I think we have two primary goals which I have listed below with possible solutions which would help accomplish these goals:

1. Production grade CI system which we can trust with full confidence and fault tolerance
    - Abstract test infrastructure from tests itself (#6108)
    - Improve test cleanup mechanism
    - Test retry to avoid false failures (not sure if we do this currently)
    - Setup health check / monitoring system for CI and test infra
    - Automated provisioning of test infra if possible
    - Process around CI maintenance like lockdown before release, etc
    - Improve reporting and dashboards
    - Improve backup and restore mechanism (we have sensible scripts but they may need updates)
    - Dynamic drone workers to scale up/down
2. Minimize build times for quick feedback
    - Run robot tests in parallel to reduce test execution time (Mike is already working on this #5601)
    - Move tests which don’t belong to CI to nightly build
    - Remove wait build script (#6108 may do this)
    - Fail-fast

Also, there are things of high priority which we would like to accomplish as follows:
- Set up CI for OVA build
    - Complete integration testing
    - End to end testing
- Separate CI for Harbor team 
- Dog-fooding
    - Run everything on VIC including CI

And there are stuff which we would like to have like below:
- Migrate from Drone to Jenkins CI
- Run tests on vSphere
- Scaling test infrastructure on demand

I hope this helps!

**Comment by mdharamadas1** [comment]
@sgairo @gigawhitlocks do we have an issue created for OVA build yet? If not I can create one so that I can start adding details there.
Also, as we cannot have epic inside epic, how do we plan to manage each of these items which seems to be an epic size for me?

**Comment by sgairo** [comment]
@mdharamadas1 What specific to OVA build? Also as far as I've been aware we have the capability to have epics inside of epics. Did someone say not to do so?

**Comment by mdharamadas1** [comment]
Ah, yes #4810 is what I was looking. Thanks!
I did hear someone saying that its not a good idea to have a epic under an epic. But @mhagen-vmware can confirm that I guess?

**Comment by chengwang86** [comment]
@gigawhitlocks @mdharamadas1 @sgairo @mhagen-vmware Do we already have an existing issue which tracks the task of refactoring current integration test in order to speed up the ci tests? E.g., for most of the docker cmd tests, we don't really need to deploy a new VCH every time we ran a new test suite.

**Comment by mhagen-vmware** [comment]
We have something better than that, a full PR that just needs a single bug fixed and our tests will run massively faster:
https://github.com/vmware/vic/pull/5601

**Comment by mdubya66** [comment]
Removing the epic from 1.3. Individual issues should be added to the releases

**Comment by mhagen-vmware** [comment]
To add to the above desires ( and some duplication), in order to get to where we want with VIC 1.3 release:

1. reliable nightlies
2. VC + VSAN within our CI
3. Implement our existing automation backlog
4. Jenkins server for nightlies and longevity
5. Automate security tests

**Comment by mhagen-vmware** [comment]
done
