### ISSUE TITLE
Analyze and Decompose Migration of VIC to containerd based storage

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#6308]
We would like to phase in support of containerd based components into the current VIC engine.  Our first attempt will be to update some of the storage components to include the metadata, content, and snapshot services.  This is a big task.  We must implement these services with an eye on containerd as well as keeping in mind the need to support these services in our current design.  The goal is to start understanding these services in the context of VIC as well as have an implementation that we can validate in the field.

Areas that will likely be affected:

1. Docker Create
1. Docker Pull
1. Docker Cp
1. Docker Diff
1. Docker Commit
1. Portlayer
1. Persona/ImageC

Acceptance Criteria:

- [ ] Functional description of metadata, content and snapshot service for VIC with description of compatibility/incompatibility with current VIC design and interfaces.
- [ ] GO Interface of metadata, content, and snapshot service with description of what purpose they serve for VIC.  An API can also do nothing.  Containerd source code must be studied to make sure the VIC stated description is compatible.
- [ ] Interaction diagram of docker pull functionality with these 3 new services.  With estimate.
- [ ] interaction diagram of docker create functionality with these 3 new services.  With estimate.
- [ ] interaction diagram of docker diff functionality with these 3 new services.  With estimate.
- [ ] interaction diagram of docker cp functionality with these 3 new services.  With estimate.
- [ ] interaction diagram of docker commit functionality with these 3 new services.  With estimate.

**Comment by sflxn** [comment]
scrum team reorged. Containerd work deprioritized for now.
