### ISSUE TITLE
Associate all VCH VMs with a named VM-Host affinity DRS rule

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#6461]
**Story**
As a viadmin I wish to ensure that all portions of a VCH are confined to a specific set of hosts within the target cluster (whether for isolation or failure domain or otherwise)

**Detail**
While the endpointVM for a VCH can be manually added to a DRS rule by a viadmin the same is not true for containerVMs that can be created at any time without viadmin intervention. In order to restrict all VMs in a VCH to a specific set of hosts requires that cVMs be associated with a DRS host affinity rule when created.
This would entail:
- [ ] vic-machine option to supply a DRS rule name
- [ ] port layer change to associate a newly created cVM with the rule
- [ ] changes to validation logic to ensure that port groups and datastores can be accessed from the host subset for a given rule (if that's even possible to determine via API)

Additional consideration should be applied to reconfiguration semantics but my initial inclination would be not to alter existing cVMs, but to update the endpointVM if the rule association changes.

Initial estimate is for finding the appropriate VMOMI API calls, determining initial viability and further decomposition work.

@malikkal

**Comment by malikkal** [comment]
Many thanks @hickeng

> vic-machine option to supply a DRS rule name
 port layer change to associate a newly created cVM with the rule
 changes to validation logic to ensure that port groups and datastores can be accessed from the host subset for a given rule (if that's even possible to determine via API)

1 & 2 is great. I don't think 3 is required, as all the datastores in a given cluster are expected to be accessible by all hosts in that cluster. IMHO, same goes for portgroup; may be some exceptions for the portgroup, although I cant think of any immediately.

**Comment by hickeng** [comment]
Initial investigation on how to add basic VCH wide DRS rule association

The vSphere calls:
1. Use `ReconfigureComputeResource_Task` to update the config of the cluster the VCH belong to - adds the need for Host.Inventory.EditCluster privilege.
2. Populate the [`ClusterConfigSpecEx.groupSpec`](http://pubs.vmware.com/vsphere-6-0/index.jsp#com.vmware.wssdk.apiref.doc/vim.cluster.ConfigSpecEx.html) field with an updated [`ClusterVmGroup`](http://pubs.vmware.com/vsphere-6-0/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.cluster.VmGroup.html)

The port layer integration:
1. Associate the VM after creation and before power-on to avoid immediate migration issues - this will need to be added to the create section of Commit. Commit is getting excessively large and should be broken out into a separate subfunction with the addition of this logic.
2. If no rule is specified then do not attempt an association - this allows us to function correctly without the cluster wide privilege.
- I'm unsure whether failure to update group should be considered a hard or soft error

vic-machine create:
1. add option for DRS VM group name
2. create group if does not exist (optional - could also error out if group doesn't exist)
3. confirm Host.Inventory.EditCluster privilege if rule is provided
4. update validator to retrieve any host restriction from rules and use the reduced host set to validate datastore/dpg - this has the added benefit that changes to the rule restriction and implications on validation can be visible in vicadmin. We will need to have vicadmin actually perform full validation, not just the subset it does currently.

vic-machine configure:
0. validate new group against the rest of the config before starting configure
1. remove cVMs and endpoint from old group, if any
2. update endpoint with new group spec (could be empty if removing group association)
2. add existing cVMs and endpoint to the new group if provided

**Comment by andrewtchin** [comment]
talk to george and make more stories for implementation of this

**Comment by zjs** [comment]
> vic-machine configure:
> 0. validate new group against the rest of the config before starting configure
> 1. remove cVMs and endpoint from old group, if any
> 2. update endpoint with new group spec (could be empty if removing group association)
> 3. add existing cVMs and endpoint to the new group if provided

Is there a risk that the vCMs would be migrated by DRS between steps 1 & 3? It seems like we want an sequence of steps that allows for essentially an "atomic swap".

**Comment by zjs** [comment]
> update validator to retrieve any host restriction from rules and use the reduced host set to validate datastore/dpg - this has the added benefit that changes to the rule restriction and implications on validation can be visible in vicadmin. We will need to have vicadmin actually perform full validation, not just the subset it does currently.

Is this actually the desired behavior?

From a usability point-of-view: It's really easy for an administrator to change the membership of the DRS Host Group, but we don't have a good way to surface errors resulting from that membership change.

From a scope point-of-view: It seems like validating only the reduced host set requires VIC to be much more aware of how DRS rules work and are used than any other aspect of this work. For example, this is the only place where VIC would need to understand the difference between "must" and "should" or Affinity and Anti-Affinity rules. It's also the only place where VIC would need to care about the number of rules defined on the DRS VM Group.

**Comment by stuclem** [comment]
Opened https://github.com/vmware/vic-product/issues/1586 to track doc effort. Removing kind/user-doc from this one.

**Comment by zjs** [comment]
Fixed in #7735.
