### ISSUE TITLE
VIC UI Testing for 1.3

### ISSUE THREAD

**Issue by jak-atx** [vmware/vic#6649]
Remaining VIC-UI testing tasks in order to be ready for 1.3 release. 

Todo:

- [X] move our nightly tests to jenkins 

~~- [ ] turn off drone publish to gcp  and turn on jenkins publish to gcp after successful nightly tests run~~

- [X] skip consistently failing tests

- [x] pull down latest ova for our testing

- [X] implement new wizard tests

- [x] pin selenium tests to stable browser

**Comment by jooskim** [comment]
> turn off drone publish to gcp and turn on jenkins publish to gcp after successful nightly tests run

It's too early to do this until we get our nightlies stabilized.

**Comment by mdubya66** [comment]
What's the status of this Epic?

**Comment by jooskim** [comment]
All the requirements were met and new test cases were added based on the ship-stopper issues with multi datacenters. I am currently making adjustments to the email report format so we get a better and succinct nightly report. Once that's done by the end of today or tomorrow I would close this Epic.
