### ISSUE TITLE
Milestone: [composite] VCH appliance restart

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#701]
This is a composite of the component parts of restarting a VCH:
- [x] Running containers need to be discovered and indexed
- [x] Name resolution needs to be populated with container names and aliases.
- [x] Existing networks need to be retrieved, and current IPAM state synthesized from network config and running containers.
- [x] Image stores need to be processed and indexed

This adds support for restarting the VCH appliance and retrieving system state from vsphere - given the appliance has no persistent state, being able to restart it is very close to being able to hand control off to a second appliance which is necessary for zero downtime upgrade.

The appliance should be responsive to requests immediately after boot where those requests don't rely on state that has yet to be restored.

**Comment by mdubya66** [comment]
GA feature from SSOD

**Comment by hickeng** [comment]
Closing this epic - the general behaviour is now implemented. Any deviation are now bugs.
