### ISSUE TITLE
Milestone: vic-machine delete

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#702]
A core part of development and deployment workflow is the ability to delete a VCH.

This should be able to:
- [x] delete all containerVMs managed by the VCH
- [x] delete all volumes managed by the VCH
- [x] delete all images managed by the VCH
- [x] delete any vSphere networks _created_ (not just used) by the VCH
- [x] remove VCH specific metadata from vSphere objects (if any)
- [x] remove the resource pool/vApp and appliance VM

We may want switches to keep volumes and images.

**Comment by corrieb** [comment]
@emlin can this be closed now?
