### ISSUE TITLE
Milestone: runtime layers

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#717]
With vmfork we have the ability to create runtime layers, such as loaded Tomcat instance, but prior to WARs being loaded.

This milestone will break down into at least three others:
- [ ] trigger fork in running containerVM
- [ ] allow referencing of runtime layer for creating a new container
- [ ] integration of runtime layer (checkpoints) into build spec.

Depends on #696

**Comment by mdubya66** [comment]
these need to be reviewed given the state of vmfork.
