### ISSUE TITLE
ROBO support - portlayer

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7223]
Grouping for the portlayer specific work:
- [ ] Host VM placement
- [ ] Utilize Inventory Folder for containerVMs

- [ ] cache invalidation on WAN link issues - may move to separate vmomi gateway epic
- [ ] event mechanism updates - may move to separate vmomi gateway epic

@cgtexmex removed _Possible: tolerance for no bridge configured_ on Feb 12
@cgtexmex removed _containerVM  limit enforcement_ on Feb 13

**Comment by mdubya66** [comment]
All issues completed. Closing.
