### ISSUE TITLE
ROBO support - Test Environment

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#7224]
ROBO has specific environment considerations that must be replicated in a test environment.  

- [x] Document Test Environment requirements
- [ ] Architect & Create ROBO Environment that emulates customer deployment
- [x] Create Smaller ROBO _like_ environment utilize vSphere Ent. Plus w/DRS Disabled
- [x] Automate ROBO Testbed deployment

**Comment by hickeng** [comment]
DRS-disabled testbed better aligns with the feature level validation used for determining placement logic. We explicitly decided against a license type check as those SKUs are prone to name changes, and content flux.
