### ISSUE TITLE
Provide License and Feature Check

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7277]
Currently vic-machine facilitates a license check on the targeted environment.  We will need to check the license and then verify that specific features are available.  The identified feature checks will have dependencies on the environment license.  Using the DRS feature as an example:

- Enterprise Plus would require DRS
- ROBO would not require DRS

- [ ] Identify license to feature mapping
- [ ] Provide means for vic components to check status of specific features (i.e. DRS)
- [ ] vic-machine updated to facilitate check
- [ ] vic-admin updated to report status (deferred)
- [ ] CI Test Plan
- [ ] CI Tests

**Comment by mdubya66** [comment]
All issues completed. Closing
