### ISSUE TITLE
VM Placement without DRS

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7282]
vic needs to provide the ability to place the VCH and the resulting containerVMs in a cluster that does not have DRS enabled.  The VM placement will attempt to prevent a bad host selection versus finding an ideal host.   Essentially, we don't want to reproduce DRS in the vic product, but do need to provide this capability for ROBO type environments.

- [ ] Placement algorithm via vic product library 
- [ ] Utilize placement library in portLayer
- [ ] Utilize placement library in vic-machine
- [ ] CI Test Plan
- [ ] CI Tests

**Comment by mdubya66** [comment]
All issues completed. Closing.
