### ISSUE TITLE
Milestone: vcsim based vic-machine test

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#732]
Use vcsim as the target for vic-machine and get a functioning 'appliance'.

Questions:
- [ ] how do we 'boot' the fakeVM and launch the components
- [ ] what do we do about iso handling - can it be ignored entirely
- [ ] need to fake guestinfo in some manner for appliance components - may need to be built with mocked datasource/sink for the extraconfig package.

Being able to mock vic-machine installs in this manner enables white box testing of:
* initial deployment
* reconfigure
* upgrade

along with various scenarios that are potentially hard for us to recreate in actual VC's (such as maxed out host configs, enormous numbers of datastores, etc.)

**Comment by mdubya66** [comment]
Moving this epic to Done

**Comment by mdubya66** [comment]
Closing as all subissues are done.
