### ISSUE TITLE
vic-machine create tests updated for folder support

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#7499]
vic-machine has been updated to utilize vSphere folders.  We need to ensure that the CI tests these changes adequately.  This includes vSphere vs. standalone ESXi.

A sample, but not exhaustive set of tests:
- [x] vic-machine creates the appliance VM in a newly created folder by the same name
- [x] vic-machine create attempts to create folders only in vCenter
- [x] vic-machine create fails with the correct error message when there is a dummy VM with the same name as the VCH in the path where the VCH folder is bring created - see #7526 
- [x] vic-machine create fails with the correct error message when there is a dummy VM with the same name as the VCH in the path where the VCH folder is bring created - see #7526 (FOLDER EDITION)
- [x] ensure containerVMs are created in the correct folder
- [x] ensure containerVMs are created in the correct folder and that only the containerVMs for a given VCH are presented via `docker ps` - from https://github.com/vmware/vic/issues/7499#issuecomment-374735325

**Comment by anchal-agrawal** [comment]
This issue has an integration test tagged against it. The test must be enabled and addressed before closing this issue. See #7526

**Comment by cgtexmex** [comment]
We need to ensure these tests also exercise the path of environments with DRS disabled (ROBO like) to ensure Container VMs are created in the correct folder and that only the ContainerVMs for a given VCH are presented via `docker ps`.

**Comment by matthewavery** [comment]
Some additional tests we may want to include here:
