### ISSUE TITLE
Wolfpack prototype 8: storage support

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#7973]
Add support for storage to the wolfpack project.

- [ ] Prototype the wolfpack storage support in the wolfpack repo
- [ ] Submit the prototype and design to the OSS community
- [ ] Add support for storage support in the wolfpack feature branch of VIC

**Comment by sflxn** [comment]
Please note, this is prototype 8.  The demo prototypes were numbered and planned ahead of time in the VIC project page in the internal confluence page.  This is not the 8th demo.  It's just adopting the numbering from that project page.

**Comment by sflxn** [comment]
The prototypes are a little out of order.  Prototype 9 must be done before prototype 8.  Without secrets support, wolfpack vms cannot talk to the cluster.
