### ISSUE TITLE
Prototype 12: Logs support

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#8126]
Add log support into the VCH for multi-container pod vms.  Today, a container vm has a single container and logs are written to the serial bus and saved on vSphere as a file.  In a pod vm, there are multiple containers.  They each need to write out their logs somewhere.  There are 3 ways to achieve this.

1. Give each container a mapped serial port.  This presents a performance issue as these virtual serial ports are handled by the ESX kernel and more of them adds further management load.  It also limits the number of containers that can run in the pod vm to the number of virtual serial port.
2. Have each container log to their local filesystem and have an agent in the pod vm forward the logs to a known external log server.
3. Switch logging from mapped serial port to namespace db, write a tether component to forward stdio to the namespace db.

At the current time, we have chosen to investigate option 3.  The tasks to achieve this are as follows,

- [ ] Add namespace db support to govmomi https://github.com/vmware/govmomi/issues/1123
- [ ] Design a time stream based mechanism to update and query the namespace db
- [ ] Write a tether component to forward stdout and stderr to the namespace db
- [ ] Add support for retrieving these logs in the vic virtual kubelet provider
