### ISSUE TITLE
Prototype 11: Attach support

### ISSUE THREAD

**Issue by sflxn** [vmware/vic#8127]
Currently, VIC's container vm only supports one container per vm isolation.  With the pod vm's multiple container support and execution of containers in the pod vm handled by runc, attach support needs to be reworked to allow attaching to each container.

- [ ] Refactor the stream proxy in the persona to allow a 2nd level id for the child container
- [ ] Refactor the interaction portlayer handler to allow a 2nd level id for the child container
- [ ] Refactor the tether to handle attaching to child containers in the pod vm.
- [ ] Add support for attaching to containers to the VIC virtual kubelet provider
