### ISSUE TITLE
High level test scenarios

### ISSUE THREAD

**Issue by hickeng** [vmware/vic#97]
Record of some of the high level vSphere scenarios that we need to have in our test suite:
- [x] [SDRS clusters](http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.vsphere.resmgmt.doc/GUID-598DF695-107E-406B-9C95-0AF961FC227A.html)
- [x] [Enhanced Linked Mode](https://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.vsphere.install.doc/GUID-91EF7282-C45A-4E48-ADB0-5A4230A91FF2.html)
- [ ] High-availability vCenter deployment (multiple vCenter appliances) - do we need to care?
- [x] Hetrogeneous ESXi host versions in cluster
- [x] Third party registries (e.g. Artifactory)
- [ ] Unusual DNS config such as multiple IPs returned

And the integration testing
- [ ] Docker datacenter able to drive VIC
